{
    'targets':[{
        'target_name':'hello',
        'sources':[
            'src/hello.cc'
        ]
    },{
        'target_name':'xmltojson',
        'sources':[
            'src/xmltojson.cc'
        ]
    }]
}
